using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SpectrumLook.Builders
{
    /// <summary>
    /// This class is used to define what kind of items that the list builders are going
    /// to generate.  All List builders use this item but some of the list builders may
    /// not use all the input fields.
    /// By Patrick Tobin
    /// </summary>
    public class Element
    {
        public override string ToString()
        {
            return Annotation + ", " + Mz.ToString("0.00");
        }

        /// <summary>
        /// This constructor currently does nothing.
        /// </summary>
        public Element()
        {
        }

        public Element(double mz, double intensity)
        {
            Mz = mz;
            Intensity = intensity;
        }

        /// <summary>
        /// This stores the annotation that is presented on the graph.  And generated by the
        /// TheoryListBuilder.
        /// </summary>
        public string Annotation { get; set; }

        /// <summary>
        /// This value stores the relative intensity that is shown on the graph and generated
        /// by the ActualListBuilder.
        /// </summary>
        public double Intensity { get; set; }

        /// <summary>
        /// This boolean value tells the ComparedListBuilder, the plot and the fragment ladder
        /// rather this value is matched or not.  This is set by the ComparedListBuilder Class.
        /// </summary>
        public bool Matched { get; set; }

        /// <summary>
        /// This is the mzValue that the plot and fragment ladder present.
        /// This value is both set by the ActualListBuilder and the TheoryListBuilder.
        /// </summary>
        public double Mz { get; set; }
    }
}
